"""Away / auto-attendant mode.

When the user is unavailable, Jarvis holds a real conversation on their behalf with anyone who
messages — not one canned line. Replies are generated by the local brain (free/unlimited), so it
can answer simple questions, take messages, and keep chatting until the user is back.
"""

from __future__ import annotations

import asyncio
from typing import Optional

_state = {"away": False, "reason": ""}
_convos: dict[str, list[dict]] = {}  # jid -> message history with that person


def set_away(reason: str = "") -> None:
    _state["away"] = True
    _state["reason"] = (reason or "").strip()
    _convos.clear()


def set_available() -> None:
    _state["away"] = False
    _state["reason"] = ""
    _convos.clear()


def is_away() -> bool:
    return _state["away"]


def reason() -> str:
    return _state["reason"]


def oneliner(config) -> str:
    """A single sensible message for channels that can't hold a conversation (calls, SMS)."""
    user = config.user_name
    why = f" ({_state['reason']})" if _state["reason"] else ""
    return f"Hi, this is {user}'s assistant — {user} is away right now{why}. I'll pass on your message."


def _system(config, sender_name: str) -> str:
    user = config.user_name
    why = f" — {user} said: {_state['reason']}" if _state["reason"] else ""
    return (
        f"You are {user}'s personal assistant, replying on their WhatsApp while {user} is away{why}. "
        f"You are chatting with {sender_name}. Be warm, brief (1-2 short sentences), and natural. "
        f"Let them know {user} isn't available right now, take a message or answer simple questions, "
        f"and keep the conversation going if they reply. Do NOT pretend to be {user} — you are the "
        f"assistant. Never invent facts about {user}'s plans beyond what you were told."
    )


async def respond(config, jid: str, sender_name: str, text: str) -> Optional[str]:
    """Generate the assistant's next reply in the ongoing conversation with `jid`, or None."""
    if not _state["away"]:
        return None
    hist = _convos.setdefault(jid, [])
    hist.append({"role": "user", "content": text})
    messages = [{"role": "system", "content": _system(config, sender_name or "them")}] + hist[-10:]

    def _call():
        from openai import OpenAI

        base_url, key, model = config.llm_params()
        client = OpenAI(base_url=base_url, api_key=key or "x", max_retries=0, timeout=45)
        r = client.chat.completions.create(model=model, messages=messages, temperature=0.6, max_tokens=200)
        return (r.choices[0].message.content or "").strip()

    try:
        reply = await asyncio.to_thread(_call)
    except Exception:  # noqa: BLE001
        reply = f"Hi, this is {config.user_name}'s assistant — they're away right now, but I'll pass on your message."
    hist.append({"role": "assistant", "content": reply})
    return reply
